M48
; DRILL file {KiCad (6.0.5)} date Sat Jun 11 17:52:37 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-11T17:52:37-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X130.518Y-100.477
X130.518Y-147.427
X155.028Y-100.477
X155.028Y-147.427
T0
M30
